pr:
- master
- develop
variables:
  buildConfiguration: 'Release'

stages:
  - stage: windowsbuild
    displayName: 'Build for Windows'
    jobs: 
    - job: build
      displayName: 'Windows Build'
      pool:
        vmImage: 'windows-latest'

      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore'
        inputs:
          command: 'restore'
          projects: '**/**/*.csproj'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: 'build'
          projects: '**/*.csproj'
        

  # - stage: windowsbuild
  #   displayName: 'Build for MacOS'
  - stage: linuxbuild
    displayName: 'Build for Linux'
    jobs: 
      - job: build
        displayName: 'Linux Build'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
        - task: DotNetCoreCLI@2
          displayName: 'Restore'
          inputs:
            command: 'restore'
            projects: '**/**/*.csproj'
            feedsToUse: 'select'
        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'build'
            projects: '**/*.csproj'

        
